//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNhomQLBH
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public int MaDH { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Size { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<int> Giamgia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
